// Mocks generated by Mockito 5.4.4 from annotations
// in muhajir_quran/test/mocks/mock_home_repository.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:mockito/mockito.dart' as _i1;
import 'package:muhajir_quran/app/base_project/components/state.dart' as _i3;
import 'package:muhajir_quran/app/home/model/quran_detail_model.dart' as _i5;
import 'package:muhajir_quran/app/home/model/quran_model.dart' as _i4;
import 'package:muhajir_quran/app/home/repository/home_repository.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [HomeRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockHomeRepository extends _i1.Mock implements _i2.HomeRepository {
  @override
  void getQuranList(
          {required _i3.ResponseHandler<List<_i4.QuranModel>?>? response}) =>
      super.noSuchMethod(
        Invocation.method(
          #getQuranList,
          [],
          {#response: response},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void getQuranDetail({
    required String? noSurah,
    required _i3.ResponseHandler<_i5.QuranDetailModel>? response,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #getQuranDetail,
          [],
          {
            #noSurah: noSurah,
            #response: response,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  dynamic mapToData(String? event) => super.noSuchMethod(
        Invocation.method(
          #mapToData,
          [event],
        ),
        returnValueForMissingStub: null,
      );
}
